// Package swift analyzes Swift source natively via internal/swiftlex — no
// subprocess, mirroring crap-metric's Go analyzer (which sits on go/ast the
// same way this sits on swiftlex).
//
// Function/init/deinit/subscript bodies are found by a single token-stream
// walk that tracks curly-brace depth, rather than a real parser. Two
// deliberate v1 scope decisions fall out of that:
//
//   - Computed-property accessors (get/set/willSet/didSet) are never
//     emitted as their own crap.Function — their bodies are brace-tracked
//     over (so they don't corrupt anything) but their complexity is simply
//     not reported, rather than guessed at with a qualified name like
//     "Type.prop.get". A natural v2 addition, not attempted here.
//   - A nested local func (a real Swift feature Go has no equivalent of)
//     found while already inside a function body is NOT emitted as its own
//     crap.Function — its branches fold into the *enclosing* function's
//     complexity count instead, exactly mirroring how Go's own analyzer
//     lets go/ast.Inspect walk nested FuncLits into the same FuncDecl's
//     count rather than double-counting. This falls out naturally from the
//     walk only looking for new function starts at the top level (outside
//     any active function body scan), not from any special-casing.
//
// Coverage comes from an lcov file (`swift test --enable-code-coverage` +
// `llvm-cov export -format=lcov`, generated by the target repo's own CI),
// parsed directly — no subprocess, same posture as the Go analyzer parsing
// `cover.out` directly. lcov's DA: lines are per-line like Python/TS's
// coverage input (not per-block like Go's), so uncovered ranges are built
// with crap.MergeLineRanges the same way the Python/TypeScript analyzers
// already do.
package swift

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"git.roost-r.com/cadeh/quality-gates/internal/analyzers"
	"git.roost-r.com/cadeh/quality-gates/internal/crap"
	"git.roost-r.com/cadeh/quality-gates/internal/swiftlex"
)

type Analyzer struct{}

func (Analyzer) Analyze(opts analyzers.Options) ([]crap.Function, error) {
	var cov lcovData
	if opts.CoveragePath != "" {
		var err error
		cov, err = parseLCOV(opts.CoveragePath)
		if err != nil {
			return nil, fmt.Errorf("parse lcov coverage report: %w", err)
		}
	}

	var out []crap.Function
	err := filepath.WalkDir(opts.Dir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			name := d.Name()
			if name == ".build" || name == ".swiftpm" || name == "Pods" || name == "Tests" ||
				(strings.HasPrefix(name, ".") && path != opts.Dir) {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".swift") || isTestFile(d.Name()) {
			return nil
		}

		fns, err := analyzeFile(path, opts.Dir, cov, opts.CoveragePath != "")
		if err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
		out = append(out, fns...)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

func isTestFile(name string) bool {
	return strings.HasSuffix(name, "Tests.swift") || strings.HasSuffix(name, "Test.swift")
}

func analyzeFile(path, dir string, cov lcovData, haveCoverage bool) ([]crap.Function, error) {
	src, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	rel, err := filepath.Rel(dir, path)
	if err != nil {
		rel = path
	}
	rel = filepath.ToSlash(rel)

	toks := swiftlex.Tokenize(src)
	fns := extractFunctions(toks)

	covLines := lookupCoverage(cov, rel)
	out := make([]crap.Function, 0, len(fns))
	for _, fn := range fns {
		total, covered, uncovered := coverageForRange(covLines, fn.startLine, fn.endLine)
		out = append(out, crap.Function{
			File:           rel,
			Name:           fn.name,
			StartLine:      fn.startLine,
			EndLine:        fn.endLine,
			Complexity:     fn.complexity,
			LinesTotal:     total,
			LinesCovered:   covered,
			UncoveredLines: crap.MergeLineRanges(uncovered),
			Unmeasured:     haveCoverage && covLines == nil,
		})
	}
	return out, nil
}

func coverageForRange(covLines map[int]bool, start, end int) (total, covered int, uncovered []int) {
	if covLines == nil {
		return 0, 0, nil
	}
	for line := start; line <= end; line++ {
		hit, measured := covLines[line]
		if !measured {
			continue
		}
		total++
		if hit {
			covered++
		} else {
			uncovered = append(uncovered, line)
		}
	}
	return total, covered, uncovered
}

// lcovData is an lcov coverage report's DA: (line, hit-count) records,
// keyed by the SF: path as written in the report.
type lcovData struct {
	files map[string]map[int]bool
}

// parseLCOV reads an lcov file, keeping only SF:/DA:/end_of_record. A file
// can appear across multiple SF:/end_of_record sections (e.g. a
// multi-target build reporting the same source more than once); a line
// counts as hit if ANY section reports a nonzero count for it.
func parseLCOV(path string) (lcovData, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return lcovData{}, err
	}

	result := lcovData{files: map[string]map[int]bool{}}
	var current string
	for _, line := range strings.Split(string(data), "\n") {
		switch {
		case strings.HasPrefix(line, "SF:"):
			current = strings.TrimSpace(strings.TrimPrefix(line, "SF:"))
			if result.files[current] == nil {
				result.files[current] = map[int]bool{}
			}
		case strings.HasPrefix(line, "DA:"):
			if current == "" {
				continue
			}
			fields := strings.Split(strings.TrimPrefix(line, "DA:"), ",")
			if len(fields) < 2 {
				continue
			}
			lineNo, err1 := strconv.Atoi(strings.TrimSpace(fields[0]))
			count, err2 := strconv.Atoi(strings.TrimSpace(fields[1]))
			if err1 != nil || err2 != nil {
				continue
			}
			if count > 0 || !result.files[current][lineNo] {
				result.files[current][lineNo] = count > 0
			}
		case line == "end_of_record":
			current = ""
		}
	}
	return result, nil
}

// lookupCoverage finds relPath's coverage map. lcov SF: paths aren't
// guaranteed relative-to-repo-root across llvm-cov invocations (often
// absolute, toolchain/build-system dependent) — match by path suffix
// rather than requiring exact equality.
func lookupCoverage(cov lcovData, relPath string) map[int]bool {
	if m, ok := cov.files[relPath]; ok {
		return m
	}
	suffix := "/" + relPath
	for k, m := range cov.files {
		k = filepath.ToSlash(k)
		if k == relPath || strings.HasSuffix(k, suffix) {
			return m
		}
	}
	return nil
}
